/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.smartcom.sdk.models

import com.squareup.moshi.Json
import java.io.Serializable


/**
 * 
 *
 * @param attributes 
 */


data class AddCustomerTokenRequestData (

    @Json(name = "attributes")
    val attributes: AddCustomerTokenRequestDataAttributes? = null

) : Serializable {


}

