/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.smartcom.sdk.models

import loymax.smartcom.sdk.models.AddCustomerTokenRequestData

import com.squareup.moshi.Json


/**
 * 
 *
 * @param `data` 
 */


data class AddCustomerTokenRequest (

    @Json(name = "data")
    val `data`: AddCustomerTokenRequestData? = null

) : java.io.Serializable {


}

