/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.smartcom.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable


/**
 * Информация о пользователе.
 *
 * @param id Идентификатор пользователя.
 * @param username Имя пользователя.
 * @param email Email пользователя.
 */



data class AuthTokenResponseDataAttributesUser (

    /* Идентификатор пользователя. */
    @Json(name = "id")
    val id: kotlin.Int? = null,

    /* Имя пользователя. */
    @Json(name = "username")
    val username: kotlin.String? = null,

    /* Email пользователя. */
    @Json(name = "email")
    val email: kotlin.String? = null

) : Serializable {


}

