/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.smartcom.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable


/**
 * 
 *
 * @param id 
 * @param mailingCatId 
 * @param name 
 * @param description 
 * @param statusEmail 
 * @param statusPush 
 * @param statusSms 
 */



data class CustomerSubscriptionCategoriesDataInnerAttributes (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "mailing_cat_id")
    val mailingCatId: kotlin.Int? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "status_email")
    val statusEmail: kotlin.String? = null,

    @Json(name = "status_push")
    val statusPush: kotlin.String? = null,

    @Json(name = "status_sms")
    val statusSms: kotlin.String? = null

) : Serializable {


}

