/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.smartcom.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable


/**
 * 
 *
 * @param type 
 * @param subtype 
 * @param `value` 
 */



data class CustomerNotificationStatusDataInnerAttributes (

    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "subtype")
    val subtype: kotlin.String? = null,

    @Json(name = "value")
    val `value`: kotlin.Int? = null

) : Serializable {


}

