/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.smartcom.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable


/**
 * 
 *
 * @param username Имя пользователя.
 * @param password Пароль пользователя.
 */



data class GetAuthTokenRequestDataAttributes (

    /* Имя пользователя. */
    @Json(name = "username")
    val username: kotlin.String,

    /* Пароль пользователя. */
    @Json(name = "password")
    val password: kotlin.String

) : Serializable {


}

