/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.smartcom.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable


/**
 * 
 *
 * @param type 
 * @param messageId 
 * @param externalClientId 
 */



data class LogPushEventRequestDataInner (

    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "message_id")
    val messageId: kotlin.String? = null,

    @Json(name = "external_client_id")
    val externalClientId: kotlin.String? = null

) : Serializable {


}

