/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.smartcom.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable


/**
 * 
 *
 * @param email 
 * @param sms 
 * @param push 
 * @param messengerColonTelegram 
 * @param messengerColonWhatsapp 
 */



data class ModifySubscriptionRequestDataAttributesCategoriesMailingCode (

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "sms")
    val sms: kotlin.String? = null,

    @Json(name = "push")
    val push: kotlin.String? = null,

    @Json(name = "messenger:telegram")
    val messengerColonTelegram: kotlin.String? = null,

    @Json(name = "messenger:whatsapp")
    val messengerColonWhatsapp: kotlin.String? = null

) : Serializable {


}

