/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.smartcom.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable


/**
 * 
 *
 * @param status Код состояния HTTP.
 * @param title Описание ошибки.
 */



data class RateLimitErrorResponseErrorsInner (

    /* Код состояния HTTP. */
    @Json(name = "status")
    val status: kotlin.Int? = null,

    /* Описание ошибки. */
    @Json(name = "title")
    val title: kotlin.String? = null

) : Serializable {


}

