/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.smartcom.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable


/**
 * 
 *
 * @param email 
 * @param push 
 * @param sms 
 */



data class SetCustomerNotificationStatusRequestDataAttributes (

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "push")
    val push: kotlin.String? = null,

    @Json(name = "sms")
    val sms: kotlin.String? = null

) : Serializable {


}

