/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.smartcom.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable


/**
 * 
 *
 * @param errors Список ошибок.
 */



data class SMCErrorResponse (

    /* Список ошибок. */
    @Json(name = "errors")
    val errors: kotlin.collections.List<SMCErrorDetails>? = null

) : Serializable {


}

