/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.smartcom.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable


/**
 * Метаинформация о коллекции. 
 *
 * @param count Количество элементов на текущей странице.
 * @param total Общее количество элементов.
 */



data class SMCMeta (

    /* Количество элементов на текущей странице. */
    @Json(name = "count")
    val count: kotlin.Int? = null,

    /* Общее количество элементов. */
    @Json(name = "total")
    val total: kotlin.Int? = null

) : Serializable {


}

