/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.popup.sdk.models

import com.squareup.moshi.Json

/**
 * @param clientId - Идентификатор клиента
 * @param sourceId – Идентификатор источника событий (Запросить у SmC).
 * @param sessionId - Идентификатор сессии
 * @param date - Дата и время события
 * @param name - Name of a web event. If passed \"user_login\" or \"user_visit\" also writes a session
 * @param container - Название контейнера, не может быть пустым "webcart","like_products", "personal_offers"
 * @param categoryId - Идентификатор категории товара
 * @param productId - Идентификатор товар
 * @param quantity - Количество
 * @param price - Стоимость
 */

data class EventRequest (

    /*  */
    @Json(name = "client_id")
    val clientId: kotlin.String,

    @Json(name = "source_id")
    val sourceId: kotlin.String,

    @Json(name = "session_id")
    val sessionId: kotlin.String,

    @Json(name = "date")
    val date: kotlin.String,

    /* Name of a web event. If passed \"user_login\" or \"user_visit\" also writes a session */
    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "container")
    val container: kotlin.String,

    @Json(name = "category_id")
    val categoryId: kotlin.String? = null,

    @Json(name = "product_id")
    val productId: kotlin.String? = null,

    @Json(name = "quantity")
    val quantity: java.math.BigDecimal? = null,

    @Json(name = "price")
    val price: java.math.BigDecimal? = null
)

